FROM php:8.2-fpm

# Atualize os pacotes e instale as dependências
RUN apt-get update && apt-get install -y \
    build-essential \
    libpng-dev \
    libjpeg62-turbo-dev \
    libfreetype6-dev \
    locales \
    jpegoptim optipng pngquant gifsicle \
    vim \
    git \
    curl \
    zip \
    unzip \
    libpq-dev \
    libzip-dev \
    libexif-dev \
    libonig-dev \
    autoconf \
    pkg-config \
    libssl-dev

WORKDIR /var/www

# Limpe o cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Instale extensões
RUN docker-php-ext-install pdo pdo_pgsql mbstring zip exif pcntl gd

# Instale a extensão phpredis usando pecl e habilite-a
RUN pecl install redis && docker-php-ext-enable redis

# Instale o composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# Adicione um usuário para a aplicação Laravel
RUN groupadd -g 1000 www
RUN useradd -u 1000 -ms /bin/bash -g www www

# Copie o conteúdo do diretório da aplicação existente
COPY . /var/www

# Copie as permissões do diretório da aplicação existente
COPY --chown=www:www . /var/www

# Ajuste de permissões
RUN chown -R www-data:www-data /var/www/application
RUN chmod -R 777 /var/www/application

# Mude o usuário atual para www
USER www

# Exponha a porta 9000 e inicie o servidor php-fpm
EXPOSE 9000
CMD ["php-fpm"]
